### ISSUE TITLE
Information about output outdated

### ISSUE THREAD

**Issue by LucasMS** [cuelee/RE2C#1]
Dear Cue Lee, 

I would like to let you know that the information about the output columns is outdated.
Currently, columns are: 
rsID Nstudy LSs LSse LSp I2 Q Qp RE2Cs1 RE2Cs2 RE2Cp* RE2Cp

So, what' s the difference between the last two columns?
Cheers,
Lucas

**Comment by cuelee** [comment]
Dear Lucas, 

Thanks for letting me know this issue.

Today, I have revised the RE2C Github main page to provide answers to your questions.
If you feel the answer to your question isn't enough, let me know that again.

I will reply to your emails soon.

**Comment by LucasMS** [comment]
Dear Cue Lee,

Thanks for this! 

I will close the issue now, ok?

All the best,
Lucas
